version: "3.9"
volumes:
  modelvolume:
services:
  pre:
    build: 
      context: ./
      dockerfile: pre_dockerfile
    volumes:
      - modelvolume:/app
  train:
    build: 
      context: ./
      dockerfile: train_dockerfile
    volumes:
      - modelvolume:/app
    depends_on:
      - pre
    links:
      - pre
  app:
    build: 
      context: ./
      dockerfile: app_dockerfile
    volumes:
      - modelvolume:/app
    ports:
      - "8050:8050"
    restart: on-failure
    depends_on:
      - train
    links:
      - train